### ISSUE TITLE
Code Review follow up tasks

### ISSUE THREAD

**Issue by jmound** [GoogleCloudPlatform/terraform-pci-starter#50]
- [x] Call out that environment (prod v non-prod) are not considered in this demo #61
- [x] Consider creating a “Known Issues” / “Gotcha” section in documentation. ie. That forsetti needs to be created before some variables can be set and re-applied #61 
- [x] Review for consistency with Google’s internal terraform standards guide #62
-  ~in `shared.tf`, separate out variables and locals into separate files~
- [x] where applicable, like where there are long service account names, use locals. [Example](https://github.com/GoogleCloudPlatform/terraform-pci-starter/blob/master/terraform/projects/in-scope/main.tf#L61) #63
- [x] Ensure commented descriptions on all IAM bindings #55 
- [x] Migrate to use CFT log-export module #54
- [x] Remove unused cluster outputs #53
